import { useState, useEffect, useCallback } from 'react'
import type { ModManifest, ModCategory, ActiveMods, AppSettings } from '../../../shared/types'
import Header from './components/Header'
import ModCard from './components/ModCard'
import SettingsPanel from './components/SettingsPanel'
import EditModal from './components/EditModal'
import './App.css'

const DETAILS: Record<ModCategory, { title: string; label: string; icon: string; folder: string; description: string }> = {
  graphics: { title: 'الجرافكس', label: 'FiveM Graphics', icon: '🎨', folder: 'mods/graphics/اسم-الجرافكس/', description: 'اختر جرافكس واحداً لتفعيله.' },
  audio: { title: 'أصوات الأسلحة', label: 'GTA V Weapon Sounds', icon: '🔊', folder: 'mods/audio/اسم-الصوت/', description: 'اختر حزمة صوت واحدة لتفعيلها.' },
  bloodfx: { title: 'BloodFX', label: 'Blood Effects', icon: '🩸', folder: 'mods/bloodfx/اسم-الحزمة/', description: 'كل حزمة تحتوي ملف DAT وملف RPF.' },
  killfx: { title: 'KillFX', label: 'Kill Effects', icon: '💥', folder: 'mods/killfx/اسم-الحزمة/', description: 'كل حزمة تحتوي ملف DAT وملف RPF.' }
}
const CATEGORIES = Object.keys(DETAILS) as ModCategory[]

export default function App() {
  const [mods, setMods] = useState<ModManifest[]>([]); const [activeCategory, setActiveCategory] = useState<ModCategory>('graphics'); const [activeMods, setActiveMods] = useState<ActiveMods>({ graphics: null, audio: null, bloodfx: null, killfx: null }); const [settings, setSettings] = useState<AppSettings>({ gtaPath: '', fivemPath: '', backupEnabled: true }); const [gtaValid, setGtaValid] = useState(false); const [fivemValid, setFivemValid] = useState(false); const [showSettings, setShowSettings] = useState(false); const [loadingId, setLoadingId] = useState<string | null>(null); const [refreshing, setRefreshing] = useState(false); const [toast, setToast] = useState<{ msg: string; type: 'success' | 'error' } | null>(null); const [showFavorites, setShowFavorites] = useState(false); const [editingMod, setEditingMod] = useState<ModManifest | null>(null); const [downloadingId, setDownloadingId] = useState<string | null>(null); const [downloadProgress, setDownloadProgress] = useState<Record<string, number>>({})
  const toastMessage = useCallback((msg: string, type: 'success' | 'error') => { setToast({ msg, type }); setTimeout(() => setToast(null), 3000) }, [])
  useEffect(() => window.api.onDownloadProgress(({ modId, progress }) => setDownloadProgress((prev) => ({ ...prev, [modId]: progress }))), [])
  const download = async (id: string) => { setDownloadingId(id); setDownloadProgress((prev) => ({ ...prev, [id]: 0 })); const result = await window.api.downloadMod(id); setDownloadingId(null); if (result.success) { await loadMods(); toastMessage('تم تحميل المود بنجاح', 'success') } else toastMessage(result.error || 'فشل التحميل', 'error') }
  const loadMods = useCallback(async () => { const list = await window.api.refreshMods(); const savedFavorites = JSON.parse(localStorage.getItem('favorites') || '[]'); const state = await window.api.getState(); const customMods = JSON.parse(state.customMods || '{}'); setMods(list.map(mod => ({ ...mod, favorite: savedFavorites.includes(mod.id), ...(customMods[mod.id] || {}) }))); return list }, [])
  useEffect(() => { async function start() { const [_, state] = await Promise.all([loadMods(), window.api.getState()]); setActiveMods(state.activeMods); setSettings(state.settings); setGtaValid(state.paths.gtaValid); setFivemValid(state.paths.fivemValid) } start() }, [loadMods])
  const activate = async (id: string) => { setLoadingId(id); const result = await window.api.activateMod(id); setLoadingId(null); if (result.success) { if (result.activeMods) setActiveMods(result.activeMods); toastMessage('تم التفعيل بنجاح', 'success') } else toastMessage(result.error || 'حدث خطأ', 'error') }
  const deactivate = async (id: string) => { setLoadingId(id); const result = await window.api.deactivateMod(id); setLoadingId(null); if (result.success) { if (result.activeMods) setActiveMods(result.activeMods); toastMessage('تم إلغاء التفعيل', 'success') } else toastMessage(result.error || 'حدث خطأ', 'error') }
  const refresh = async () => { setRefreshing(true); await loadMods(); setRefreshing(false); toastMessage('تم تحديث القائمة', 'success') }
  const save = async (next: AppSettings) => { const result = await window.api.saveSettings(next); setSettings(next); setGtaValid(result.paths.gtaValid); setFivemValid(result.paths.fivemValid); toastMessage('تم حفظ الإعدادات', 'success') }
  const toggleFavorite = (id: string) => { setMods(prev => prev.map(mod => mod.id === id ? { ...mod, favorite: !mod.favorite } : mod)); const favorites = mods.map(m => m.id === id ? { ...m, favorite: !m.favorite } : m).filter(m => m.favorite).map(m => m.id); localStorage.setItem('favorites', JSON.stringify(favorites)) }
  const handleEdit = (mod: ModManifest) => { setEditingMod(mod) }
  const handleSaveEdit = async (updatedMod: ModManifest) => { setMods(prev => prev.map(m => m.id === updatedMod.id ? updatedMod : m)); await window.api.saveCustomMod(updatedMod.id, { nameAr: updatedMod.nameAr, descriptionAr: updatedMod.descriptionAr }); setEditingMod(null); toastMessage('تم حفظ التعديلات', 'success') }
  const detail = DETAILS[activeCategory]; const list = showFavorites ? mods.filter((mod) => mod.favorite) : mods.filter((mod) => mod.category === activeCategory)
  return <div className="app" dir="rtl"><Header gtaValid={gtaValid} fivemValid={fivemValid} onOpenSettings={() => setShowSettings(true)} onRefresh={refresh} refreshing={refreshing} /><main className="main-content"><nav className="category-switcher"><div className="categories-left">{CATEGORIES.map((category) => <button key={category} className={activeCategory === category && !showFavorites ? 'selected' : ''} onClick={() => { setActiveCategory(category); setShowFavorites(false) }}>{DETAILS[category].icon} {DETAILS[category].title}<span>{mods.filter((mod) => mod.category === category).length}</span></button>)}</div><button className={`favorites-btn ${showFavorites ? 'active' : ''}`} onClick={() => { setShowFavorites(!showFavorites); setActiveCategory('graphics') }}>★ المفضلة<span>{mods.filter((mod) => mod.favorite).length}</span></button></nav><section className={`content-heading ${showFavorites ? 'blur-transition' : ''}`}><div><p className="eyebrow">{showFavorites ? 'المفضلة' : detail.label}</p><h2>{showFavorites ? 'المفضلة' : detail.title}</h2><p>{showFavorites ? 'المودات المفضلة لديك' : detail.description}</p></div><span className="mods-count">{list.length} متاح</span></section>{list.length ? <div className="mods-grid">{list.map((mod) => <ModCard key={mod.id} mod={mod} isActive={activeMods[mod.category] === mod.id} loading={loadingId === mod.id} downloading={downloadingId === mod.id} progress={downloadProgress[mod.id] || 0} onActivate={activate} onDeactivate={deactivate} onDownload={download} onToggleFavorite={toggleFavorite} onEdit={handleEdit} />)}</div> : <div className="empty-state"><span className="icon">{showFavorites ? '★' : detail.icon}</span><p>{showFavorites ? 'لا توجد مودات مفضلة' : 'لا توجد حزم في هذا التصنيف'}</p><p className="hint">{showFavorites ? 'أضف مودات للمفضلة من خلال زر ...' : `أنشئ مجلداً لكل حزمة داخل<br /><strong>${detail.folder}</strong><br />ثم ضع الملفات بداخله واضغط تحديث.`}</p></div>}</main>{showSettings && <SettingsPanel settings={settings} onSave={save} onClose={() => setShowSettings(false)} />}{editingMod && <EditModal mod={editingMod} onClose={() => setEditingMod(null)} onSave={handleSaveEdit} />}{toast && <div className={`toast ${toast.type}`}>{toast.msg}</div>}</div>
}
